// Generated by uniffi-bindgen-react-native
#include "rrn-mobile-ffi.h"
#include "rrn_mobile_ffi.hpp"

namespace rrnmobileffi {
	using namespace facebook;

	uint8_t installRustCrate(jsi::Runtime &runtime, std::shared_ptr<react::CallInvoker> callInvoker) {
		NativeRrnMobileFfi::registerModule(runtime, callInvoker);
		return true;
	}

	uint8_t cleanupRustCrate(jsi::Runtime &runtime) {
		return false;
	}
}