// Generated by uniffi-bindgen-react-native
#ifdef __cplusplus
#import "rrn-mobile-ffi.h"
#endif

#ifdef RCT_NEW_ARCH_ENABLED
#import "RNNativeModuleSpec.h"

@interface RrnMobileFfi : NSObject <NativeRrnMobileFfiSpec>
#else
#import <React/RCTBridgeModule.h>

@interface RrnMobileFfi : NSObject <RCTBridgeModule>
#endif

@end