#include <jni.h>
#include <fbjni/fbjni.h>
#include "RrnDiscoveryOnLoad.hpp"

// Entry point when `System.loadLibrary("RrnDiscovery")` runs (see the generated
// RrnDiscoveryOnLoad.kt). Everything it registers — the JNI natives and the
// "StationDiscovery" hybrid-object constructor — is generated by nitrogen.
JNIEXPORT jint JNICALL JNI_OnLoad(JavaVM* vm, void*) {
  return facebook::jni::initialize(vm, []() {
    margelo::nitro::rrndiscovery::registerAllNatives();
  });
}
